# -*- coding: utf-8 -*-
"""prodigy-ds-task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tM-C_z8ujXTiGpu7FpdavWTGBTMAZBKt

Data Cleaning and Exploratory Data Analysis of the Titanic Dataset
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
files.upload()

data = pd.read_csv("train.csv")
data

data.isnull().sum() #This will show how many missing values exist in each column

#addresing missing values
data["Age"] = data["Age"].fillna(data["Age"].median())
data["Sex"] = data["Sex"].map({"male":0, "female":1})

#bar chart
sns.countplot(x="Survived", data=data)
plt.show()

sns.barplot(x="Pclass", y="Survived", data=data)
plt.show()

#density plot
sns.displot(x="Age", hue="Survived", data=data, kind="kde")
plt.show()